### ISSUE TITLE
Write a Tutorial From First Principals using Phoenix LiveView to Sync Cursors on a Canvas/Page

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-liveview-realtime-cursor-tracking-tutorial#1]
One of the "killer" features of `Pheonix` and now `LiveView` is the low cost websockets 
for realtime communication between _many_ connected browsers. 

# Todo

+ [x] Write an example/tutorial from scratch that showcases cursors on a page.
+ [x] Integrate with `auth` / `auth_plug` to display names and avatars (profile pictures) next to the cursor
+ [ ] Deploy to Fly.io (new org) so the demo is permanently up.

For context on _why_ we have so many separate repos to demonstrate tiny experiments, please read: https://github.com/dwyl/technology-stack/issues/96

**Comment by nelsonic** [comment]
@SimonLab shared via Signal: https://koenvangilst.nl/blog/phoenix-liveview-cursors
https://github.com/vnglst/phoenix_cursors + https://github.com/vnglst/liveview_cursors

Reading ...

**Comment by nelsonic** [comment]
@SimonLab if you want to pick this up it would be _awesome_ to have a step-by-step tutorial. 🙏 
We will 100% be using this feature in our App so understanding how _everything_ works from first principals is paramount.

**Comment by nelsonic** [comment]
@LuchoTurtle take a look at this and if you want to pick it up please go for it! 🙏 
@SimonLab already has a _lot_ on with other tasks ... https://github.com/orgs/dwyl/projects/14?fullscreen=true 📥 
it would be awesome to get this done soon. 🤞

**Comment by nelsonic** [comment]
This is useful in a teamwork setting where it's good to see someone else's cursor moving around the page. 🖱️ 
E.g. if we're re-ordering `items` for priority during a live backlog grooming session. 💭 
If we can get this working, we will 100% integrate it into our App. :shipit: 
The _mega_ challenge will be translating mouse/cursor movement on different screen sizes ... 📱 + 🖥️ 
i.e. the "real world" implementation of this requires some math. 🤓

**Comment by LuchoTurtle** [comment]
@nelsonic can you add me as a contributor? I didn't fork the repo and I wanted to create a PR to show the progress so far but I'm getting a 403. Is that possible? 
<img width="1042" alt="Screenshot 2022-10-20 at 20 36 04" src="https://user-images.githubusercontent.com/17494745/197041651-b2a39c7f-5eb4-4d2d-a80b-44a07e4453be.png">

Thank you!

**Comment by nelsonic** [comment]
@LuchoTurtle what is your branch? are you trying to push to `main`? 
Please confirm you now have **`admin`** (***`owner`***) access. 👌

**Comment by LuchoTurtle** [comment]
> @LuchoTurtle what is your branch? are you trying to push to `main`? 
> Please confirm you now have **`admin`** (***`owner`***) access. 👌 

It's another branch on this repo. I've yet to push it ☺️

**Comment by nelsonic** [comment]
Could we pick up the **`auth`** part of this quest at some point?  🙏 🔒 
It would be great to display the _actual_ name and avatar of the `person`. 👤

**Comment by LuchoTurtle** [comment]
I'll take a look at this once the Edit Timer PR is taken care of 👍

**Comment by LuchoTurtle** [comment]
The https://github.com/dwyl/phoenix-liveview-realtime-cursor-tracking-tutorial/pull/12 PR should fix this. 
The CI is failing because there is no `AUTH_API` env variable. 
Waiting on a response from here https://github.com/dwyl/phoenix-liveview-realtime-cursor-tracking-tutorial/pull/12#issuecomment-1325500751 , and it's quickly mergeable.

**Comment by nelsonic** [comment]
@LuchoTurtle having **`owner`** (**`admin`**) access to _every_ repo in the org 
means you can _always_ add GitHub Actions secrets, 
e.g: https://github.com/dwyl/phoenix-liveview-realtime-cursor-tracking-tutorial/settings/secrets/actions

You don't need to ask for permission or _wait_ ... ⏳ 
just follow the instructions in the [**`auth_plug` docs**](https://github.com/dwyl/auth_plug#2-get-your-auth_api_key-) and add the **`AUTH_API_KEY`** using the GitHub UI.

e.g: https://authdemo.fly.dev/apps/6

![image](https://user-images.githubusercontent.com/194400/203653925-c74aea9b-2161-449f-98b9-c1c3798c606f.png)

![image](https://user-images.githubusercontent.com/194400/203654046-9dfe8045-c649-4238-b4f1-b5094f93458c.png)

![auth-api-key-github-actions-secret-set](https://user-images.githubusercontent.com/194400/203654413-c11fe7d9-0c16-4601-9579-55395166f9b7.png)



> **Note**: Don't worry, this **`AUTH_API_KEY`** is not valid, it was reset immediately and updated:
![image](https://user-images.githubusercontent.com/194400/203654335-999ab92d-31b6-4318-9f3c-679ce8e47e87.png)


Also added an **`AUTH_API_KEY`** secret to: https://fly.io/apps/live-cursors/secrets
![image](https://user-images.githubusercontent.com/194400/203655722-575f584e-0888-4724-ae18-fdff7c532a6f.png)

So deployment should work too. ✅

**Comment by nelsonic** [comment]
https://live-cursors.fly.dev/login ⏳
